# Form implementation generated from reading ui file '.\main_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(547, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=MainPage)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineedit_path = QtWidgets.QLineEdit(parent=self.frame)
        self.lineedit_path.setObjectName("lineedit_path")
        self.horizontalLayout.addWidget(self.lineedit_path)
        self.button_select = QtWidgets.QPushButton(parent=self.frame)
        self.button_select.setObjectName("button_select")
        self.horizontalLayout.addWidget(self.button_select)
        self.button_watch = QtWidgets.QPushButton(parent=self.frame)
        self.button_watch.setObjectName("button_watch")
        self.horizontalLayout.addWidget(self.button_watch)
        self.button_stop = QtWidgets.QPushButton(parent=self.frame)
        self.button_stop.setObjectName("button_stop")
        self.horizontalLayout.addWidget(self.button_stop)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 244, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        self.button_select.setText(_translate("MainPage", "Select Folder"))
        self.button_watch.setText(_translate("MainPage", "Watch"))
        self.button_stop.setText(_translate("MainPage", "Stop"))
